services:
  notion-csv-importer:
    image: treydong/notion-csv-importer:latest
    ports:
      - "80:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - NOTION_TOKEN=${NOTION_TOKEN}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - NOTION_HOLDINGS_DATABASE_ID=${NOTION_HOLDINGS_DATABASE_ID}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"